// frontend/react-app/src/App.tsx
// frontend/react-app/src/App.tsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import './App.css';

// Hardcoded API keys (intentional)
const API_KEY = 'sk_live_react_api_key_123456';  // Secret detection test
const GOOGLE_MAPS_KEY = 'AIzaSyBhardcoded_maps_key_789';  // Another secret

interface User {
  id: number;
  name: string;
  email: string;
  creditCard?: string;  // PII detection test
}

const App: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [userInput, setUserInput] = useState('');

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      // Insecure API call with hardcoded credentials
      const response = await axios.get('/api/users', {
        headers: {
          'Authorization': `Bearer ${API_KEY}`,  // Hardcoded secret usage
          'X-API-Key': GOOGLE_MAPS_KEY
        }
      });
      setUsers(response.data);
    } catch (error) {
      console.error('Failed to fetch users:', error);
    }
  };

  // XSS vulnerability (intentional)
  const handleSearch = (event: React.FormEvent) => {
    event.preventDefault();
    const resultDiv = document.getElementById('search-results');
    if (resultDiv) {
      // Dangerous innerHTML usage
      resultDiv.innerHTML = `<h3>Search results for: ${searchTerm}</h3>`;  // XSS risk
    }
  };

  // Unsafe eval usage (intentional)
  const calculateExpression = () => {
    try {
      // Code injection vulnerability
      const result = eval(userInput);  // Dangerous eval usage
      alert(`Result: ${result}`);
    } catch (error) {
      alert('Invalid expression');
    }
  };

  // Local storage of sensitive data (intentional)
  const saveUserData = (user: User) => {
    // Storing sensitive data in localStorage
    localStorage.setItem('currentUser', JSON.stringify(user));  // Security risk
    localStorage.setItem('apiKey', API_KEY);  // Storing secrets in localStorage
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>CSB React Security Test App</h1>
        
        {/* Search functionality with XSS vulnerability */}
        <form onSubmit={handleSearch}>
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search users..."
          />
          <button type="submit">Search</button>
        </form>
        <div id="search-results"></div>

        {/* Expression calculator with code injection */}
        <div>
          <h3>Calculator (Dangerous)</h3>
          <input
            type="text"
            value={userInput}
            onChange={(e) => setUserInput(e.target.value)}
            placeholder="Enter math expression..."
          />
          <button onClick={calculateExpression}>Calculate</button>
        </div>

        {/* User list with potential data exposure */}
        <div>
          <h3>Users</h3>
          {users.map(user => (
            <div key={user.id} onClick={() => saveUserData(user)}>
              <p>Name: {user.name}</p>
              <p>Email: {user.email}</p>
              {/* Displaying sensitive data */}
              {user.creditCard && <p>Credit Card: {user.creditCard}</p>}
            </div>
          ))}
        </div>
      </header>
    </div>
  );
};

export default App;

// frontend/angular-app/src/app/app.component.ts
// frontend/angular-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

// Hardcoded secrets (intentional)
const API_ENDPOINT = 'https://api.csb.com/v1';
const SECRET_TOKEN = 'bearer_token_angular_app_456789';  // Secret detection test
const AWS_ACCESS_KEY = 'AKIAIOSFODNN7EXAMPLE123';  // AWS key detection

interface UserData {
  id: number;
  name: string;
  email: string;
  ssn?: string;  // PII detection test
}

@Component({
  selector: 'app-root',
  template: `
    <div class="container">
      <h1>CSB Angular Security Test App</h1>
      
      <!-- XSS vulnerability through bypassing sanitization -->
      <div [innerHTML]="unsafeHtml"></div>
      
      <!-- Form with potential injection -->
      <form (ngSubmit)="submitData()">
        <input [(ngModel)]="userInput" placeholder="Enter data">
        <button type="submit">Submit</button>
      </form>
      
      <!-- Display sensitive data -->
      <div *ngFor="let user of users">
        <p>{{user.name}} - {{user.email}}</p>
        <p *ngIf="user.ssn">SSN: {{user.ssn}}</p>
      </div>
    </div>
  `
})
export class AppComponent implements OnInit {
  title = 'csb-angular-security-test';
  users: UserData[] = [];
  userInput = '';
  unsafeHtml: SafeHtml = '';

  constructor(
    private http: HttpClient,
    private sanitizer: DomSanitizer
  ) {}

  ngOnInit() {
    this.loadUsers();
    this.setupUnsafeContent();
  }

  loadUsers() {
    // Insecure HTTP call with hardcoded credentials
    const headers = {
      'Authorization': SECRET_TOKEN,  // Hardcoded secret usage
      'X-AWS-Access-Key': AWS_ACCESS_KEY
    };

    this.http.get<UserData[]>(`${API_ENDPOINT}/users`, { headers })
      .subscribe(
        data => this.users = data,
        error => console.error('Error loading users:', error)
      );
  }

  submitData() {
    // Unsafe evaluation (intentional)
    try {
      const result = eval(`"Result: " + ${this.userInput}`);  // Code injection
      alert(result);
    } catch (error) {
      console.error('Evaluation error:', error);
    }

    // Store sensitive data in localStorage
    localStorage.setItem('userInput', this.userInput);
    localStorage.setItem('apiToken', SECRET_TOKEN);  // Storing secrets
  }

  setupUnsafeContent() {
    // Bypassing Angular's sanitization (dangerous)
    const unsafeContent = '<script>alert("XSS")</script><p>Unsafe content</p>';
    this.unsafeHtml = this.sanitizer.bypassSecurityTrustHtml(unsafeContent);  // XSS risk
  }

  // Weak random number generation
  generateSessionId(): string {
    return Math.random().toString(36);  // Cryptographically weak
  }

  // Insecure cookie handling
  setCookie(name: string, value: string) {
    document.cookie = `${name}=${value}`;  // No secure/httpOnly flags
  }
}
